### ISSUE TITLE
Frequent "Match error: Failed Match.OneOf or Match.Optional validation" messages on server side

### ISSUE THREAD

**Issue by bohan0** [percolatestudio/find-from-publication#5]
I am getting a lot of these types of messages on the Meteor server side terminal output.

```
I20151002-18:48:30.810(0)? Exception from sub recentPosts id K42kw2vAkK5wxawTv Error: Match error: Failed Match.OneOf or Match.Optional validation
I20151002-18:48:30.811(0)?     at checkSubtree (packages/check/match.js:244:1)
I20151002-18:48:30.811(0)?     at check (packages/check/match.js:32:1)
I20151002-18:48:30.811(0)?     at [object Object]._.extend._getFindOptions (packages/mongo/collection.js:244:1)
I20151002-18:48:30.811(0)?     at [object Object]._.extend.find (packages/mongo/collection.js:280:1)
I20151002-18:48:30.812(0)?     at [object Object].<anonymous> (server/publications.js:459:21)
I20151002-18:48:30.812(0)?     at [object Object]._handler (packages/percolate_find-from-publication/packages/percolate_find-from-publication.js:49:1)
I20151002-18:48:30.812(0)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151002-18:48:30.812(0)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151002-18:48:30.813(0)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151002-18:48:30.813(0)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151002-18:48:30.813(0)? Sanitized and reported to the client as: Match failed [400]
```

How should investigate this problem (if it is a problem)?

Here is the publish function:

```
 FindFromPublication.publish('recentPosts', function (limit) {
    var username = getUsername(this.userId);
    return Articles.find({
      author: username
    }, {
      sort: {
        createdAt: -1
      },
      limit: limit
    });
  });
```

**Comment by sebakerckhof** [comment]
Sorry we could never get to this, but this package has been largely rewritten since this bug report, so closing
