### ISSUE TITLE
Meteor.users.findFromPublication gets only the current user if the current user is updated since 1.3

### ISSUE THREAD

**Issue by trajano** [percolatestudio/find-from-publication#7]
I have a non-trivial application at the moment, so it's going to be a bit difficult to extract the part of code that is causing the issue.

However, I am using "alanning:roles" and I found that when data on the current user gets updated the subscription will only have the current user.  However, it's not consistent as of yet.  I am in the midst of putting in console.log statements in your code to see what may be causing the problem.

The problem started manifesting in Meteor 1.3.

**Comment by trajano** [comment]
after adding some logging, I see that it adds initially, but something triggers it to remove all the data again.  It seems to clear off the whole thing because it removes other collections such as counts.  These log statements were added to `this.added( ...)` and `this.removed(...)`
  So I am guessing it may be something to do with how Meteor.publish works now.

<pre>
I20160403-00:21:53.926(-4)? added users pQzMkc5hpt7iSZH8g
I20160403-00:21:53.928(-4)? added users 8iJyS2j6ADrMS97FQ
I20160403-00:21:53.930(-4)? added users HwcnJo2jqtZomL6TK
I20160403-00:21:53.932(-4)? added users DzhZE4gGhwBoz2n7q
I20160403-00:21:53.933(-4)? added users szL962cAkYY3pFrdr
I20160403-00:21:53.933(-4)? added users XkJAytoH4m5dzd8Gh
I20160403-00:21:53.935(-4)? added users R4XYzcRZSMBBcGmZH
I20160403-00:21:53.935(-4)? added users Fk9fhg562GBZbtm6A
I20160403-00:21:53.935(-4)? added users AN9Cqt8cZMegrWEgG
I20160403-00:21:53.935(-4)? added users nuLFbNa768qMG46Mj
I20160403-00:21:54.059(-4)? removed counts venue-list-admin-count
I20160403-00:21:54.060(-4)? removed venues frwyYoeMss8iSvWLC
I20160403-00:21:54.060(-4)? removed counts user-list-admin-count
I20160403-00:21:54.063(-4)? removed users pQzMkc5hpt7iSZH8g
I20160403-00:21:54.064(-4)? removed users 8iJyS2j6ADrMS97FQ
I20160403-00:21:54.064(-4)? removed users HwcnJo2jqtZomL6TK
I20160403-00:21:54.064(-4)? removed users DzhZE4gGhwBoz2n7q
I20160403-00:21:54.064(-4)? removed users szL962cAkYY3pFrdr
I20160403-00:21:54.068(-4)? removed users XkJAytoH4m5dzd8Gh
I20160403-00:21:54.068(-4)? removed users R4XYzcRZSMBBcGmZH
I20160403-00:21:54.068(-4)? removed users Fk9fhg562GBZbtm6A
I20160403-00:21:54.068(-4)? removed users AN9Cqt8cZMegrWEgG
I20160403-00:21:54.068(-4)? removed users nuLFbNa768qMG46Mj
</pre>

**Comment by trajano** [comment]
I placed a stack trace to see what I can can determine and I noticed it was triggered by a stopSubscription which I guess is valid, I do stop the subscription after I retrieve the first set of data in my `resolve` block, but I try to get it again and attach it to the proper scope in the main controller function.  It may be a timing issue.  

<pre>
I20160403-00:37:24.122(-4)? Error
I20160403-00:37:24.122(-4)?     at Subscription.removed (server/find-from-publication-server.js:38:19)
I20160403-00:37:24.122(-4)?     at packages/ddp-server/livedata_server.js:1148:16
I20160403-00:37:24.122(-4)?     at Function._.each._.forEach (packages\underscore.js:142:22)
I20160403-00:37:24.123(-4)?     at packages/ddp-server/livedata_server.js:1147:11
I20160403-00:37:24.123(-4)?     at Function._.each._.forEach (packages\underscore.js:147:22)
I20160403-00:37:24.123(-4)?     at packages/ddp-server/livedata_server.js:1144:9
I20160403-00:37:24.123(-4)?     at Object.Meteor._noYieldsAllowed (packages\meteor.js:664:12)
I20160403-00:37:24.123(-4)?     at Subscription._removeAllDocuments (packages/ddp-server/livedata_server.js:1143:12)
I20160403-00:37:24.123(-4)?     at Session._stopSubscription (packages/ddp-server/livedata_server.js:856:30)
</pre>

**Comment by trajano** [comment]
For the moment I have commented out the part where I stop() the handle and everything is working, but I am presuming I have a subscription leak at this point.

```
          var resolved = false
          var handle = Meteor.subscribe('user-list-admin', ...
            {
              onReady: () => {
                resolve(Meteor.users.findFromPublication('user-list-admin', {}, {
                  sort: initialControllerState.sort
                }).fetch())
                resolved = true
          //      handle.stop()
              },
              onStop: () => resolved || reject()
            }
          )
```

**Comment by trajano** [comment]
Noticed that if I do that some other issues crop about namely the data remains there so I can't do search filters.

My thought is something needs to change on this.removed so that it will not remove from collection ID if there is another subscription using it.

**Comment by trajano** [comment]
So this is what I did, seems to be working so far

```
  this.removed = function(collection, id) {
    // the only way this can get called is when all documents are removed
    // from the subscription as it's torn down, we know that the underlying document
    // will also be removed, and this will pick it up.
    if (collection === METADATA_COLLECTION) {
      return
    }

    oldRemoved(METADATA_COLLECTION, constructId(collection, name, id))
    // commented this line out
    //oldRemoved(collection, id)
  }
```

Though I think there'd be reprecussions on that namely data that should be removed isn't.  Though by making this change the behaviour for my publications are working again.

**Comment by trajano** [comment]
So one effect of doing the change above appears to be Counts no longer works as I had expected.

**Comment by trajano** [comment]
I have a fix that seems to make it work with both Counts and my searches.  I'll create a PR, but I need someone to verify whether it is a proper fix or not.

**Comment by trajano** [comment]
Good news on my part (at least so far...)

I was able to create a sample with two different subscriptions against the same collection and seems to be working well so far.  (I'll post the project up later).  I even have it so it is published and retrieved as-is.

So the only thing I can think of that may be different between the app I am working on and this one is that I may have a publication that relies on something in the Meteor.users table and I am also doing a Meteor.publishWithRelations() now.

**Comment by trajano** [comment]
Actually I'll close off this bug, if I can replicate the problem with Meteor.publishWithRelations() I'll make a new one specific to it.
